/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#6e0a12",
        "surface-variant": "#e3e3dc",
        "on-error": "#fff7f6",
        tertiary: "#7b573f",
        "tertiary-fixed": "#fecdaf",
        "on-primary-container": "#295959",
        "secondary-container": "#c9ecbe",
        "surface-dim": "#dadad4",
        outline: "#7a7b76",
        "inverse-on-surface": "#9e9d99",
        "error-container": "#fa746f",
        secondary: "#486743",
        "primary-container": "#baeceb",
        "on-primary-fixed": "#134647",
        "on-background": "#31332f",
        "surface-tint": "#376767",
        "inverse-surface": "#0e0e0c",
        "outline-variant": "#b2b2ac",
        background: "#fbf9f5",
        "on-secondary-fixed-variant": "#45633f",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#e0fffe",
        "on-secondary-container": "#3b5936",
        "inverse-primary": "#cbfdfd",
        "tertiary-container": "#fecdaf",
        error: "#a83836",
        "secondary-fixed-dim": "#bbdeb1",
        "primary-fixed": "#baeceb",
        "error-dim": "#67040d",
        "surface-bright": "#fbf9f5",
        "on-secondary-fixed": "#294625",
        "surface-container-high": "#e9e8e3",
        "on-primary-fixed-variant": "#346363",
        "tertiary-fixed-dim": "#efc0a2",
        "on-surface": "#31332f",
        "on-secondary": "#eaffe1",
        "on-tertiary-fixed-variant": "#6f4c36",
        primary: "#376767",
        "secondary-dim": "#3c5a37",
        "on-surface-variant": "#5e605b",
        surface: "#fbf9f5",
        "on-tertiary-container": "#65432d",
        "surface-container": "#efeee8",
        "secondary-fixed": "#c9ecbe",
        "surface-container-low": "#f5f4ef",
        "on-tertiary-fixed": "#4f311c",
        "surface-container-highest": "#e3e3dc",
        "on-tertiary": "#fff7f4",
        "primary-dim": "#2b5a5b",
        "primary-fixed-dim": "#addddd",
        "tertiary-dim": "#6e4b34",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
